"""adding terms column

Revision ID: 374b5279b034
Revises: d73c6e400a6a
Create Date: 2025-09-15 20:41:59.767126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '374b5279b034'
down_revision: Union[str, None] = 'd73c6e400a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('terms_and_condition_followed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'terms_and_condition_followed')
    # ### end Alembic commands ###
