"""adding the Crop Recommendations table

Revision ID: 6b6e9433f2c3
Revises: da2f72131e1e
Create Date: 2025-09-18 02:09:35.628243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6e9433f2c3'
down_revision: Union[str, None] = 'da2f72131e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('predicted_crop', sa.String(length=100), nullable=False),
    sa.Column('suitability_score', sa.String(length=50), nullable=True),
    sa.Column('best_planting_time', sa.String(length=255), nullable=True),
    sa.Column('harvest_period', sa.String(length=255), nullable=True),
    sa.Column('water_requirements', sa.Text(), nullable=True),
    sa.Column('fertilizer_recommendations', sa.Text(), nullable=True),
    sa.Column('soil_condition', sa.Text(), nullable=True),
    sa.Column('expected_yield', sa.Text(), nullable=True),
    sa.Column('expected_market_price', sa.Text(), nullable=True),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_recommendations_id'), 'crop_recommendations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crop_recommendations_id'), table_name='crop_recommendations')
    op.drop_table('crop_recommendations')
    # ### end Alembic commands ###
