"""adding the crop guidances(planners) tanble

Revision ID: e87251672c06
Revises: 6665c34a0aff
Create Date: 2025-09-18 11:52:32.985597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e87251672c06'
down_revision: Union[str, None] = '6665c34a0aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_guidance_table',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('land_size', sa.Float(), nullable=False),
    sa.Column('soil_type', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('irrigation_method', sa.String(length=50), nullable=False),
    sa.Column('fertilizer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('equipment', sa.String(length=200), nullable=True),
    sa.Column('planting_date', sa.Date(), nullable=True),
    sa.Column('growing_season', sa.String(length=50), nullable=True),
    sa.Column('guidance_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_guidance_table_id'), 'crop_guidance_table', ['id'], unique=False)
    op.create_index(op.f('ix_crop_guidance_table_user_id'), 'crop_guidance_table', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crop_guidance_table_user_id'), table_name='crop_guidance_table')
    op.drop_index(op.f('ix_crop_guidance_table_id'), table_name='crop_guidance_table')
    op.drop_table('crop_guidance_table')
    # ### end Alembic commands ###
